version: '2'
services:
  mysql163:
    image: mysql163
    container_name: mysql163
    networks:
      - default
    ports:
      - "3336:3306"
    expose:
      - "3306"
  spider163:
    image: spider163
    container_name: spider163
    ports:
      # 将容器端口与宿主机绑定, 以便外部访问
      - "1163:1163"
    links:
      - mysql163:mysql163.localhost
    networks:
      - default
networks:
  default:
    external:
      name: spider163
